# Generated by Django 5.2 on 2025-06-30 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('full_name', models.CharField(blank=True, max_length=201)),
                ('age', models.PositiveIntegerField()),
                ('class_name', models.CharField(choices=[('S1', 'Senior 1'), ('S2', 'Senior 2'), ('S3', 'Senior 3'), ('S4', 'Senior 4'), ('S5', 'Senior 5'), ('S6', 'Senior 6')], max_length=10)),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ENG', 'English'), ('MTC', 'Math'), ('SCI', 'Science'), ('SST', 'Social Studie'), ('RE', 'Religious Education')], max_length=10)),
                ('score', models.PositiveBigIntegerField()),
                ('type', models.CharField(choices=[('BOT', 'Beginning of Term'), ('MOT', 'Mid Term'), ('EOT', 'End of Term'), ('MOCK', 'Mock examination'), ('TEST', 'Test')], max_length=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.subject'),
        ),
    ]
