# Generated by Django 5.2.1 on 2025-06-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='term',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
