# Generated by Django 5.2 on 2025-06-30 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='studentportal.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
