# Generated by Django 5.2 on 2025-07-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0003_alter_student_password_alter_student_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('ENG', 'English'), ('MTC', 'Math'), ('SCI', 'Science'), ('SST', 'Social Studies'), ('RE', 'Religious Education')], max_length=10),
        ),
    ]
