# Generated by Django 5.2 on 2025-07-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0004_alter_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
    ]
